mqtt:
  broker: tcp://192.168.1.251:1883
  clientId: mqttx_chengyunlai
  username: admin
  password: public
  timeout: 2000
  KeepAlive: 0
  topics: toWeb
  qos: 1
logging:
  config: classpath:logback-spring.xml
server:
  tomcat:
    uri-encoding: UTF-8
